trigger:
- main

pool:
  name: Default   # your agent pool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: NuGetAuthenticate@1

- script: dotnet restore
- script: dotnet build --configuration Release

- script: >
    dotnet pack JoyalArtifactsSolution/JoyalArtifactsSolution.csproj
    --configuration Release
    --output $(Build.ArtifactStagingDirectory)

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'JoyalArtifactsProject/joyal-feed'